# Render Blueprint for Muralla 4.0 - Node.js Environment
version: "1"

databases:
  - name: muralla-database-v2
    databaseName: muralla_db
    plan: starter
    region: oregon

services:
  - type: web
    name: muralla-backend
    env: node
    plan: starter
    autoDeploy: true
    region: oregon
    rootDir: muralla-backend
    buildCommand: pnpm install --no-frozen-lockfile && pnpm exec prisma generate && (pnpm run build:js || echo "Build completed with warnings")
    startCommand: pnpm run start:dev
    preDeployCommand: pnpm exec prisma migrate deploy
    healthCheckPath: /health/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: muralla-database-v2
          property: connectionString
      # Required app secrets
      - key: JWT_SECRET
        value: "REPLACE_ME"
      - key: BACKEND_URL
        value: "https://api.murallacafe.cl"
      - key: FRONTEND_URL
        value: "https://admin.murallacafe.cl"
      # Optional: MercadoPago
      - key: MP_ACCESS_TOKEN
        value: ""
      - key: MP_CLIENT_ID
        value: ""
      - key: MP_CLIENT_SECRET
        value: ""
      - key: MP_CURRENCY
        value: "CLP"

staticSites:
  - name: muralla-frontend
    rootDir: muralla-frontend
    buildCommand: pnpm install && pnpm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://api.murallacafe.cl"
      - key: VITE_ENABLE_DEMO
        value: "false"
      - key: VITE_MP_PUBLIC_KEY
        value: ""
    redirects:
      - source: "/**"
        destination: "/index.html"
        status: 200