# Render Blueprint for Muralla 4.0 - Node.js Environment
version: "1"

databases:
  - name: muralla-database-v2
    databaseName: muralla_db
    plan: free
    region: oregon

services:
  - type: web
    name: muralla-backend
    env: node
    plan: starter
    autoDeploy: true
    region: oregon
    rootDir: muralla-backend
    buildCommand: rm -f ../pnpm-workspace.yaml && pnpm install --no-frozen-lockfile --ignore-scripts && npx prisma generate && pnpm run build:js
    startCommand: pnpm run start
    preDeployCommand: npx prisma migrate deploy
    healthCheckPath: /health/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: muralla-database-v2
          property: connectionString
      # Required app settings (non-sensitive)
      - key: BACKEND_URL
        value: "https://api.murallacafe.cl"
      - key: FRONTEND_URL
        value: "https://admin.murallacafe.cl"
      - key: ADMIN_USER
        value: "Admin"
      - key: ADMIN_EMAIL
        value: "contacto@murallacafe.cl"
      - key: SECONDARY_ADMIN_USER
        value: "Kaví Doi"
      - key: SECONDARY_ADMIN_EMAIL
        value: "kavi@murallacafe.cl"
      - key: TERTIARY_ADMIN_USER
        value: "Darwin Bruna"
      - key: TERTIARY_ADMIN_EMAIL
        value: "darwin@murallacafe.cl"
      - key: MP_CURRENCY
        value: "CLP"
      - key: OPENFACTURA_BASE_URL
        value: "https://api.haulmer.com"
      - key: COMPANY_RUT
        value: "78188363-8"

      # ------------------------------------------------------------------
      # IMPORTANT: The following secrets MUST be set in the Render Dashboard
      # Go to Environment > Secret Files / Environment Variables
      # ------------------------------------------------------------------
      # - JWT_SECRET
      # - ADMIN_PASSWORD
      # - SECONDARY_ADMIN_PASSWORD
      # - TERTIARY_ADMIN_PASSWORD
      # - MP_PUBLIC_KEY
      # - MP_ACCESS_TOKEN
      # - MP_CLIENT_ID
      # - MP_CLIENT_SECRET
      # - TUU_API_KEY
      # - OPENFACTURA_API_KEY
      # - CLOUDINARY_CLOUD_NAME
      # - CLOUDINARY_API_KEY
      # - CLOUDINARY_API_SECRET

  - type: web
    name: muralla-frontend
    runtime: static
    plan: free
    buildCommand: rm -rf node_modules dist && npm ci && npm run build:prod
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://api.murallacafe.cl"
      - key: VITE_WS_URL
        value: "https://api.murallacafe.cl"
      - key: VITE_ENABLE_DEMO
        value: "false"
      - key: VITE_MP_PUBLIC_KEY
        value: "APP_USR-3ec5c4d9-f346-41e5-b21c-ea71cad09749"
    routes:
      - type: rewrite
        source: "/**"
        destination: "/index.html"