# Render Blueprint for Muralla 4.0 - Node.js Environment
version: "1"

databases:
  - name: muralla-database-v2
    databaseName: muralla_db
    plan: free
    region: oregon

services:
  - type: web
    name: muralla-backend
    env: node
    plan: starter
    autoDeploy: true
    region: oregon
    rootDir: muralla-backend
    buildCommand: rm -f ../pnpm-workspace.yaml && pnpm install --no-frozen-lockfile --ignore-scripts && npx prisma generate && pnpm run build:js
    startCommand: pnpm run start
    preDeployCommand: npx prisma migrate deploy
    healthCheckPath: /health/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: muralla-database-v2
          property: connectionString
      # Required app secrets
      - key: JWT_SECRET
        value: "WDKZqFHF3VKHGbVOUH059pmbQNurEApQSECyOg5pfP8="
      - key: BACKEND_URL
        value: "https://api.murallacafe.cl"
      - key: FRONTEND_URL
        value: "https://admin.murallacafe.cl"
      # Admin user creation on startup
      - key: ADMIN_USER
        value: "Admin"
      - key: ADMIN_EMAIL
        value: "contacto@murallacafe.cl"
      - key: ADMIN_PASSWORD
        value: "Muralla2025"
      - key: SECONDARY_ADMIN_USER
        value: "Kaví Doi"
      - key: SECONDARY_ADMIN_EMAIL
        value: "kavi@murallacafe.cl"
      - key: SECONDARY_ADMIN_PASSWORD
        value: "Muralla2025"
      - key: TERTIARY_ADMIN_USER
        value: "Darwin Bruna"
      - key: TERTIARY_ADMIN_EMAIL
        value: "darwin@murallacafe.cl"
      - key: TERTIARY_ADMIN_PASSWORD
        value: "Muralla2025"
      # Optional: MercadoPago
      - key: MP_ACCESS_TOKEN
        value: ""
      - key: MP_CLIENT_ID
        value: ""
      - key: MP_CLIENT_SECRET
        value: ""
      - key: MP_CURRENCY
        value: "CLP"
      # Storage Services
      - key: CLOUDINARY_CLOUD_NAME
        value: "daqkotj1t"
      - key: CLOUDINARY_API_KEY
        value: "839819221611429"
      - key: CLOUDINARY_API_SECRET
        value: "Lbrmb6nc2CHccJYsjJqTc-hjE3I"
      - key: AWS_REGION
        value: "us-east-1"
      - key: AWS_ACCESS_KEY_ID
        value: "REPLACE_WITH_ACTUAL_KEY"
      - key: AWS_SECRET_ACCESS_KEY
        value: "REPLACE_WITH_ACTUAL_SECRET"
      - key: AWS_S3_BUCKET_NAME
        value: "muralla-files"

  - type: web
    name: muralla-frontend
    runtime: static
    plan: free
    rootDir: muralla-frontend
    buildCommand: rm -f ../pnpm-workspace.yaml && npm install && npm run build:prod
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://api.murallacafe.cl"
      - key: VITE_ENABLE_DEMO
        value: "false"
      - key: VITE_MP_PUBLIC_KEY
        value: ""
    routes:
      - type: rewrite
        source: "/**"
        destination: "/index.html"