-- AlterTable
ALTER TABLE "public"."products" ADD COLUMN     "availableInCafe" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "availableOnPedidosya" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "availableOnRappi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "availableOnUber" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "cafePrice" DECIMAL(10,2),
ADD COLUMN     "displayName" TEXT,
ADD COLUMN     "images" TEXT[],
ADD COLUMN     "maxOrderQuantity" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "minOrderQuantity" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "pedidosyaPrice" DECIMAL(10,2),
ADD COLUMN     "pedidosyaProductId" TEXT,
ADD COLUMN     "rappiPrice" DECIMAL(10,2),
ADD COLUMN     "rappiProductId" TEXT,
ADD COLUMN     "uberPrice" DECIMAL(10,2),
ADD COLUMN     "uberProductId" TEXT;
