[variables]
NODE_VERSION = "20.19.0"

[phases.install]
cmds = [
  "corepack enable && corepack prepare pnpm@8.15.0 --activate",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm run start"