[variables]
NODE_VERSION = "20.19.0"

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "npm run start:prod"

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "npm run start:prod" 